# Copyright 2019 ETH Zurich and University of Bologna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


before_script:
  - pwd

# after_script:
#   - echo "stage finished"

stages:
  - fetch
  - build
  - test

fetch_tests:
  stage: fetch
  script:
    - echo "Fetching tests"
    - make test-checkout-gitlab
  artifacts:
    paths:
      - tests/*

fetch_ips:
  stage: fetch
  script:
    - echo "Fetching IPs"
    - make checkout
  artifacts:
    paths:
      - ips/*
      - sim/*
      - ipstools/*

# This jobs result is too large to produce an artifact
# fetch_sdk:
#   stage: fetch
#   script:
#     - echo "Fetching SDK from releases and setting up paths"
#     - make sdk-gitlab
#   artifacts:
#     paths:
#       - pkg/
#       - env/

build_rtl:
  stage: build
  before_script:
    - tree
    - echo "Fetching SDK from releases and setting up paths"
    - make sdk-gitlab
  script:
    - echo "Compiling RTL model and DPI libraries"
    - make build
    - echo "Installing scripts"
    - make install
    - echo "Elaborating RTL model"
    - make vopt
  artifacts:
    paths:
      - tests/*
      - ips/*
      - sim/*
      - ipstools/*
      - install/*
#      - pkg/* # sdk is too large

test_all:
  stage: test
  before_script:
    - echo "Fetching SDK from releases and setting up paths"
    - make sdk-gitlab
  script:
    - echo "Running Tests"
    - make test
  artifacts:
    reports:
      junit: tests/junit-reports/TEST-*.xml
